version: '3'
services:
  db:
    image: "roboticsmicrofarms/romidb"
    volumes:
      - ${ROMI_DB}:/home/${USER}/db
    ports:
      - "5000:5000"
    healthcheck:
      test: "exit 0"
  viewer:
    image: "roboticsmicrofarms/plantviewer"
    depends_on:
      - db
    environment:
        REACT_APP_API_URL: http://localhost:5000
    ports:
      - "3000:3000"
